version: '3.7'

services:
  intelligait_app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./intelligait_app:/intelligait_app
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    environment:
      - DEBUG=0